### ISSUE TITLE
Migrate Lines and Charts page

### ISSUE THREAD

**Issue by xiaohai-huang** [FHFHockey-dev/fhfhockey.com#7]
I encountered some issues when converting "Lines" and "Charts" page.

## **Lines** - [https://fhfhockey.com/lines](https://fhfhockey.com/lines)
The Lines page is empty.

## **Charts** - [https://fhfhockey.com/charts](https://fhfhockey.com/charts)
The Charts page looks incomplete to me, I am not sure if I should add it to the website.

![charts page](https://user-images.githubusercontent.com/56380096/178212952-ccd2afa2-494b-487c-98fe-b1111140d674.png)

**Comment by xiaohai-huang** [comment]
@FHFHockey Has provided the updated `charts.html`. I am going to migrate that to Next.js tomorrow.

[charts.zip](https://github.com/FHFHockey-dev/fhfhockey.com/files/9084642/charts.zip)

**Comment by FHFHockey** [comment]
- Line Chart for TOI is extending past 100%, and is way too tall height wise. The problem is a result of not knowing how to scrape the HTML reports, and instead using the NHL API to "try" to determine TotalPPTOI per game. The result has been inconsistent and wrong more often than not. 
- I have a Mongo Database that has the data required to finish filling in the boxes listed under sustainability. Boxes should show blue if they are in a sustainable range compared to career averages, and red if they are too far outside a sustainable range. 
- Implementation to the charts of viewing their Last 7, 14, 30 days needs to be integrated

**Comment by xiaohai-huang** [comment]
Create separate issues for these two pages #14
